version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    restart: "on-failure"
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    restart: "on-failure"
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  db:
    image: postgres:13.7-alpine
    volumes:
      - /data/postgresql/shareit-db
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: pg_isready -U postgres -d shareit
      interval: 10s
      timeout: 5s
      retries: 5