DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "items" CASCADE;
DROP TABLE IF EXISTS "requests" CASCADE;
DROP TABLE IF EXISTS "bookings" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(512) NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE "requests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "description" VARCHAR(2048) NOT NULL,
  "requester_id" BIGINT NOT NULL,
  "created" TIMESTAMP NOT NULL,
  "item_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(2048) NOT NULL,
  "owner_id" BIGINT NOT NULL,
  "status" BOOLEAN,
  "request_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "bookings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "start_date_time" TIMESTAMP NOT NULL,
  "end_date_time" TIMESTAMP NOT NULL,
  "item_id" BIGINT,
  "booker_id" BIGINT,
  "status" varchar(50),
  PRIMARY KEY ("id")
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "text" VARCHAR(2048) NOT NULL,
  "item_id" BIGINT,
  "author_id" BIGINT,
  "created" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "requests" ADD CONSTRAINT "fk_request_users" FOREIGN KEY ("requester_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "items" ADD CONSTRAINT "fk_item_users" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "items" ADD CONSTRAINT "fk_item_requests" FOREIGN KEY ("request_id") REFERENCES "requests" ("id") ON DELETE CASCADE;

ALTER TABLE "bookings" ADD CONSTRAINT "fk_booking_users" FOREIGN KEY ("booker_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "bookings" ADD CONSTRAINT "fk_booking_item" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON DELETE CASCADE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comment_users" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comment_items" FOREIGN KEY ("item_id") REFERENCES "items" ("id") ON DELETE CASCADE;
